require("file-loader?name=[name].[ext]!./index.html");
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import store from "./store";
import App from "./App";

//centralized system
sessionStorage.setItem(
  "blueberrytoken",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5YWViODE5Mi01MDEzLTQyNWQtYjIzYy0yYTZiNzA3ZDYzM2IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTUyNDIiLCJJRFVzZXIiOiIxNTI0MiIsIklEUm9sZSI6IjgiLCJNYXJrQXNBZG1pbiI6IkZhbHNlIiwiSURIUkJyYW5jaCI6IjEiLCJJRERlcGFydG1lbnQiOiIxIiwiY29tcGFueSI6IjE3IiwiSXNUZW1wb3JhcnlTZXNzaW9uRW5hYmxlZCI6IkZhbHNlIiwiSXNOZXdseUFkZWQiOiJGYWxzZSIsIklzRGVwYXJ0bWVudEhlYWQiOiJGYWxzZSIsIlJlbWVtYmVyTWUiOiJGYWxzZSIsIkZ1bGxOYW1lIjoiTmFyZXNoIE51ciBEYXYiLCJwaWRSZWZGb3JFZGl0IjoiRGF2QDEiLCJleHAiOjE2NjIxOTc0MDUsImlzcyI6Imh0dHA6Ly9teXNpdGUuY29tIiwiYXVkIjoiaHR0cDovL215c2l0ZS5jb20ifQ.LI-xdVBFFX0M1FKe5afMO7KO2T3YAmMj42gsK5oPiNc"
);
sessionStorage.setItem(
  "blueberryrefreshtoken",
  "QXv0F2SNHs0GKGfDdj1d/5UViNjSIToCsSZm9xuL1Os="
);

// sessionStorage.setItem(
//   "blueberrytoken",
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1ZjBmODA2Yy04YzE3LTQzZTUtOTRhZC0wYTIzN2VkNzAwYTkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTUxNDQiLCJJRFVzZXIiOiIxNTE0NCIsIklEUm9sZSI6IjgiLCJNYXJrQXNBZG1pbiI6IkZhbHNlIiwiSURIUkJyYW5jaCI6IjEiLCJJRERlcGFydG1lbnQiOiIxIiwiY29tcGFueSI6IjIiLCJJc1RlbXBvcmFyeVNlc3Npb25FbmFibGVkIjoiRmFsc2UiLCJJc05ld2x5QWRlZCI6IkZhbHNlIiwiSXNEZXBhcnRtZW50SGVhZCI6IkZhbHNlIiwiUmVtZW1iZXJNZSI6IkZhbHNlIiwiRnVsbE5hbWUiOiJOb3NoYW50YSBLdW1hciBTaW5naCIsInBpZFJlZkZvckVkaXQiOiJOTi0xIiwiZXhwIjoxNjU2NjY1MDU3LCJpc3MiOiJodHRwOi8vbXlzaXRlLmNvbSIsImF1ZCI6Imh0dHA6Ly9teXNpdGUuY29tIn0.DQ4wnvCgU8F8tBupoIM8ropvFwfpOlXElO7DXpo_A6E"
// );
// sessionStorage.setItem(
//   "blueberryrefreshtoken",
//   "w7sk3QMTYzbMnEvfstFD8LjMAK+co4vTwTdbSpsFGQc="
// );

// sessionStorage.setItem(
//   "blueberrytoken",
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MWIyNzc5ZC0yMTk5LTRhM2MtOWYwYi02YmUzMGQ1M2E0ZDAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMTUxNjIiLCJJRFVzZXIiOiIxNTE2MiIsIklEUm9sZSI6IjgiLCJNYXJrQXNBZG1pbiI6IkZhbHNlIiwiSURIUkJyYW5jaCI6IjEiLCJJRERlcGFydG1lbnQiOiIxIiwiY29tcGFueSI6IjIiLCJJc1RlbXBvcmFyeVNlc3Npb25FbmFibGVkIjoiRmFsc2UiLCJJc05ld2x5QWRlZCI6IkZhbHNlIiwiSXNEZXBhcnRtZW50SGVhZCI6IkZhbHNlIiwiUmVtZW1iZXJNZSI6IkZhbHNlIiwiRnVsbE5hbWUiOiJCaWplbmRyYSAgVGFtYW5nIiwicGlkUmVmRm9yRWRpdCI6Ik4yIiwiZXhwIjoxNjU2MjUwODI1LCJpc3MiOiJodHRwOi8vbXlzaXRlLmNvbSIsImF1ZCI6Imh0dHA6Ly9teXNpdGUuY29tIn0.YHvzmq4JBBVmCe7xEhifkdIRb2g5uoKXce4RbzaKAJ0"
// );
// sessionStorage.setItem(
//   "blueberryrefreshtoken",
//   "3tBPNqNfTLUKmo6A7hrnZ1/1poWFIRIf242dF2YBfpc="
// );

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById("app")
);
